TaskFlowApp/TaskFlowApp

- build.gradle
- src/main/resources/application.yml
JWT 관련해서 필요한 의존성 및 설정(yml 파일에) 추가하였습니다
어떤 변경 사항이 있나요?
> Feat/auth JWT 의존성, 설정(yml) 추가

- src/main/java/com/taskflowapp/common/response/ApiResponse.java
- src/main/java/com/taskflowapp/common/response/JsonIncludeAnnotaionExplain.md
- src/main/java/com/taskflowapp/common/response/LocalDateTimeAndInstant.md
- src/main/java/com/taskflowapp/common/response/PageResponse.java
> Feat/dashboard ApiResponse, PageResponse 완

- build.gradle
- src/main/java/com/taskflowapp/common/ApiResponse.java
- src/main/java/com/taskflowapp/domain/auth/controller/AuthController.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthLoginRequest.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthRegisterRequest.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthWithdrawRequest.java
- src/main/java/com/taskflowapp/domain/auth/dto/response/AuthLoginResponse.java
- src/main/java/com/taskflowapp/domain/auth/dto/response/AuthRegisterResponse.java
- src/main/java/com/taskflowapp/domain/auth/service/AuthService.java
- src/main/java/com/taskflowapp/domain/security/AuthUser.java
- src/main/java/com/taskflowapp/domain/security/JwtAuthFilter.java
- src/main/java/com/taskflowapp/domain/security/JwtProvider.java
- src/main/java/com/taskflowapp/domain/security/SecurityConfig.java
- src/main/java/com/taskflowapp/domain/security/TokenPayload.java
- src/main/java/com/taskflowapp/domain/security/UserDetailsImpl.java
- src/main/java/com/taskflowapp/domain/security/UserDetailsServiceImpl.java
- src/main/java/com/taskflowapp/domain/security/WebConfig.java
- src/main/java/com/taskflowapp/domain/user/controller/UserController.java
- src/main/java/com/taskflowapp/domain/user/dto/response/UserResponse.java
- src/main/java/com/taskflowapp/domain/user/enums/UserRole.java
- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
- src/main/java/com/taskflowapp/domain/user/service/UserService.java
- src/main/resources/application.yml
인증 인가(JWT, Spring Security), 회원가입, 로그인, 현재 유저 목록 조회 구현
어떤 변경 사항이 있나요?
> Feat/auth 인증 인가, 회원가입, 로그인, 현재 유저 목록 조회 구현

- src/main/java/com/taskflowapp/domain/team/dto/TeamResponse.java
- src/main/java/com/taskflowapp/domain/team/entity/Team.java
- src/main/java/com/taskflowapp/domain/user/controller/MemberController.java
- src/main/java/com/taskflowapp/domain/user/controller/UserController.java
- src/main/java/com/taskflowapp/domain/user/dto/request/MemberRequestDto.java
- src/main/java/com/taskflowapp/domain/user/dto/response/MemberResponseDto.java
- src/main/java/com/taskflowapp/domain/user/entity/User.java
- src/main/java/com/taskflowapp/domain/user/service/MemberService.java
#17 
team에 member 등록 및 조회, 삭제 기능 구현
어떤 변경 사항이 있나요?
정적팩토리 메서드 구현, 중복 예외 메세지 개선
> Feat/members - Member 등록 및 조회, 삭제 기능 구현

- src/main/java/com/taskflowapp/domain/auth/constant/AuthConstant.java
- src/main/java/com/taskflowapp/domain/auth/dto/response/AuthRegisterResponse.java
- src/main/java/com/taskflowapp/domain/auth/service/AuthService.java
- src/main/java/com/taskflowapp/domain/user/controller/UserController.java
- src/main/java/com/taskflowapp/domain/user/enums/UserRole.java
1. 관리자 Role 지정
아이디(유저네임): admin
이메일: admin@example.com
로 회원가입 시 관리자(ADMIN)로 지정
2. AuthResponse 누락 추가
어떤 변경 사항이 있나요?
> Feat/auth 관리자 Role 지정, AuthResponse 누락 추가

- src/main/java/com/taskflowapp/domain/user/controller/UserController.java
- src/main/java/com/taskflowapp/domain/user/dto/response/AssigneeResponse.java
- src/main/java/com/taskflowapp/domain/user/service/UserService.java
- AssigneeResponse 생성
- User 콘트롤러, 서비스에 필요한 로직 구현
어떤 변경 사항이 있나요?
> [user] feat: 새 작업(Task) 등록시 담당자 조회 구현

- src/main/java/com/taskflowapp/domain/user/controller/MemberController.java
- src/main/java/com/taskflowapp/domain/user/dto/response/MemberResponseDto.java
- src/main/java/com/taskflowapp/domain/user/service/MemberService.java
memberResponseDto에 정적팩토리 메서드 추가 및 member 추가 및 제거의 관리자 권한 로직 구현
어떤 변경 사항이 있나요?
공통 에러 응답에 대한 논의가 필요하다..
> Feat/members - memberResponseDto에 정적팩토리 메서드 추가 및 member 추가 및 제거의 관리자 권한 로직 구현

- src/main/java/com/taskflowapp/domain/task/dto/TaskResponse.java
- src/main/java/com/taskflowapp/domain/task/service/TaskService.java
[task] feat : takseService에 AssigneeResponse 매핑
어떤 변경 사항이 있나요?
> [task] feat : taskService에 AssigneeResponse 매핑

- src/main/java/com/taskflowapp/domain/auth/controller/AuthController.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthLoginRequest.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthRegisterRequest.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthWithdrawRequest.java
- src/main/java/com/taskflowapp/domain/auth/service/AuthService.java
- 회원탈퇴 구현(현재 물리적 삭제)
- request 입력값 조건(NotBlank, Siz, Pattern 등) 추가
어떤 변경 사항이 있나요?
> Feat/auth 회원탈퇴 구현, request 입력값 조건(NotBlank, Siz, Pattern 등) 추가

- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
- src/main/java/com/taskflowapp/domain/user/service/MemberService.java
members 팀 멤버 목록 조회를 각 팀에 속한 팀의 멤버들만 출력되도록 수정하였고
멤버의 중복 방지를 추가 가능한 사용자 목록 조회에서 검증을 미리하여 유저가 중복으로 팀에 추가되지 않도록 수정하였음.
어떤 변경 사항이 있나요?
공통 응답 예외처리에 대한 논의 필요
> feat/members - members 팀 멤버 목록 조회 및 팀 멤버 관리: 추가/삭제 (중복 방지, 존재 여부 검증)

- src/main/java/com/taskflowapp/common/SoftDelete.java
- src/main/java/com/taskflowapp/common/entity/BaseEntity.java
- src/main/java/com/taskflowapp/domain/auth/dto/request/AuthRegisterRequest.java
- src/main/java/com/taskflowapp/domain/auth/service/AuthService.java
- src/main/java/com/taskflowapp/domain/security/UserDetailsServiceImpl.java
- src/main/java/com/taskflowapp/domain/user/entity/User.java
- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
- src/main/java/com/taskflowapp/domain/user/service/UserService.java
- 회원가입시 이메일 정규식 보다 엄격하게 수정
-  role 반환 수정
- UserService에서 사용하지 않는 불필요한 코드 삭제
- Soft Delete 구현: 
- Soft Delete 클래스 생성
- 회원탈퇴시 논리적 삭제 및 팀과의 연관관계 null 처리 구현
- 논리적 삭제된 유저 제외 조회 구현
어떤 변경 사항이 있나요?
> Feat/auth 회원 탈퇴시 논리적 삭제 구현 등

- src/main/java/com/taskflowapp/domain/user/controller/UserController.java
- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
- src/main/java/com/taskflowapp/domain/user/service/UserService.java
- URL 오타 수정
- 새 작업 등록시 담당자 조회에서 Soft Delete된 유저 제외
어떤 변경 사항이 있나요?
> Feat/user 오타 수정 및 논리적 삭제된 유저 조회 제외

- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
- src/main/java/com/taskflowapp/domain/user/service/MemberService.java
- 팀 멤버 등록 시 Soft Delete된 유저 제외
어떤 변경 사항이 있나요?
> [members] feat: 팀 멤버 등록 시 Soft Delete된 유저 제외

- src/main/java/com/taskflowapp/domain/task/controller/TaskController.java
- src/main/java/com/taskflowapp/domain/task/repository/TaskRepository.java
- src/main/java/com/taskflowapp/domain/task/service/TaskService.java
> Feat/task : status별 조회 적용, 중복 Task 조회 문제 해결

- src/main/java/com/taskflowapp/domain/team/entity/Team.java
- src/main/java/com/taskflowapp/domain/user/controller/MemberController.java
- src/main/java/com/taskflowapp/domain/user/controller/UserController.java
- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.md
- src/main/java/com/taskflowapp/domain/user/service/MemberService.java
메서드명 변경 및 불필요한 로직 제거, 예외 처리 수정
어떤 변경 사항이 있나요?
> [Feat]- 메서드명 변경 및 불필요한 로직 제거, 예외 처리 수정

- src/main/java/com/taskflowapp/common/response/ApiResponse.java
- src/main/java/com/taskflowapp/domain/task/controller/TaskController.java
- src/main/java/com/taskflowapp/domain/task/entity/Task.java
- src/main/java/com/taskflowapp/domain/task/repository/TaskRepository.java
- src/main/java/com/taskflowapp/domain/task/service/TaskService.java
- src/main/java/com/taskflowapp/domain/user/repository/UserRepository.java
> [task] taskRepository 재병합

- src/main/java/com/taskflowapp/domain/comment/controller/CommentController.java
- src/main/java/com/taskflowapp/domain/comment/repository/CommentRepository.java
- src/main/java/com/taskflowapp/domain/comment/repository/CommentRepositoryQueries.md
- src/main/java/com/taskflowapp/domain/comment/service/CommentService.java
- 댓글 삭제 시 메시지 분기 로직 추가 (대댓글 포함 여부에 따라 응답 메시지 변경)
- 댓글 레포지토리 쿼리문 전체 정리 문서 추가
어떤 변경 사항이 있나요?
> [comment] 댓글 삭제 메시지 분기 로직 추가 및 레포지토리 쿼리문 정리 문서 작성

- src/main/java/com/taskflowapp/domain/dashboard/controller/DashboardController.java
- src/main/java/com/taskflowapp/domain/task/dto/TaskResponse.java
- src/main/java/com/taskflowapp/domain/task/repository/TaskRepository.java
- src/main/java/com/taskflowapp/domain/task/service/TaskService.java
> [task]refact: response 정적 메서드를 통해 리팩토링

- src/main/java/com/taskflowapp/domain/auth/service/AuthQueryLog.md
- src/main/java/com/taskflowapp/domain/dashboard/controller/DashboardController.java
- src/main/java/com/taskflowapp/domain/user/service/UserQueryLog.md
> Feat/auth 쿼리문 파일 추가

- src/main/java/com/taskflowapp/domain/activity/controller/ActivityController.java
- src/main/java/com/taskflowapp/domain/activity/dto/response/ActivityResponse.java
- src/main/java/com/taskflowapp/domain/activity/entity/Activity.java
- src/main/java/com/taskflowapp/domain/activity/repository/ActivityRepository.java
- src/main/java/com/taskflowapp/domain/activity/service/ActivityService.java
- src/main/java/com/taskflowapp/domain/comment/service/CommentService.java
- src/main/java/com/taskflowapp/domain/dashboard/controller/DashboardController.java
- src/main/java/com/taskflowapp/domain/security/filter/JwtAuthFilter.md
- src/main/java/com/taskflowapp/domain/task/controller/TaskController.java
- src/main/java/com/taskflowapp/domain/task/service/TaskService.java
- src/main/java/com/taskflowapp/domain/team/dto/TeamRequest.java
- src/main/java/com/taskflowapp/domain/user/dto/response/UserResponse.java
> Feat 전체적 오타 수정

- README.md
> feat/readme 수정 반영
